{{- if not (include "varroa.isHive" .) }}
{{- $secretName := printf "%s-nats-creds" .Release.Name -}}
{{- include "varroa.nats.creds" $ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "varroa.labels" . | nindent 4 }}
type: Opaque
data:
  operator-password: {{ $.natsCreds.operator | b64enc }}
  gateway-password: {{ $.natsCreds.gateway | b64enc }}
  bff-password: {{ $.natsCreds.bff | b64enc }}
  ca.crt: {{ $.natsCreds.caCert | b64enc }}
  ca.key: {{ $.natsCreds.caKey | b64enc }}
  tls.crt: {{ $.natsCreds.tlsCert | b64enc }}
  tls.key: {{ $.natsCreds.tlsKey | b64enc }}

{{- end }}
