{{- if not (include "varroa.isHive" .) }}
{{- if .Values.dex.enabled }}
{{- $dexIssuer := .Values.dex.config.issuer | default (printf "https://dex.%s" .Values.global.domain) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "varroa.fullname" (dict "Release" .Release "name" "dex") }}
  labels:
    app.kubernetes.io/component: dex
    {{- include "varroa.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.yaml: |
    issuer: {{ $dexIssuer | quote }}
    {{- range $key, $val := .Values.dex.config }}
    {{- if ne $key "issuer" }}
    {{ $key }}:
      {{- toYaml $val | nindent 6 }}
    {{- end }}
    {{- end }}
    {{- if and .Values.dex.grpcApi.enabled (not (hasKey .Values.dex.config "grpc")) }}
    grpc:
      addr: 0.0.0.0:{{ .Values.dex.service.grpcPort }}
    {{- end }}
{{- end }}

{{- end }}
