{{- if not (include "varroa.isHive" .) }}
{{- if .Values.dex.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "varroa.fullname" (dict "Release" .Release "name" "dex") }}
  labels:
    app.kubernetes.io/component: dex
    {{- include "varroa.labels" . | nindent 4 }}
{{- end }}

{{- end }}
