{{- if .Values.operator.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "varroa.fullname" (dict "Release" .Release "name" "varroa-operator") }}
  labels:
    app.kubernetes.io/component: varroa-operator
    {{- include "varroa.labels" . | nindent 4 }}
{{- end }}
