{{- if not (include "varroa.isHive" .) }}
{{- if (index .Values "oauth2-proxy").enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "varroa.fullname" (dict "Release" .Release "name" "oauth2-proxy") }}
  labels:
    app.kubernetes.io/component: oauth2-proxy
    {{- include "varroa.labels" . | nindent 4 }}
{{- end }}

{{- end }}
