// Code generated by cmd/protogen; DO NOT EDIT.

package mitev1

import (
	"context"
	"encoding/json"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

type CommandResult struct {
	CommandId   string                 `json:"command_id"`
	Success     bool                   `json:"success"`
	Error       string                 `json:"error,omitempty"`
	Deferred    bool                   `json:"deferred,omitempty"`
	DeferReason string                 `json:"defer_reason,omitempty"`
	HttpStatus  int                    `json:"http_status,omitempty"`
	Result      isCommandResult_result `json:"-"`
}

type isCommandResult_result interface {
	isCommandResult_result()
}

type CommandResult_DesiredState struct {
	DesiredState *DesiredStateResult `json:"desired_state,omitempty"`
}

func (*CommandResult_DesiredState) isCommandResult_result() {}

func (m *CommandResult) MarshalJSON() ([]byte, error) {
	type alias struct {
		CommandId    string              `json:"command_id"`
		Success      bool                `json:"success"`
		Error        string              `json:"error,omitempty"`
		Deferred     bool                `json:"deferred,omitempty"`
		DeferReason  string              `json:"defer_reason,omitempty"`
		HttpStatus   int                 `json:"http_status,omitempty"`
		DesiredState *DesiredStateResult `json:"desired_state,omitempty"`
	}
	var a alias
	a.CommandId = m.CommandId
	a.Success = m.Success
	a.Error = m.Error
	a.Deferred = m.Deferred
	a.DeferReason = m.DeferReason
	a.HttpStatus = m.HttpStatus
	switch v := m.Result.(type) {
	case *CommandResult_DesiredState:
		a.DesiredState = v.DesiredState
	}
	return json.Marshal(a)
}

func (m *CommandResult) UnmarshalJSON(data []byte) error {
	var a struct {
		CommandId    string              `json:"command_id"`
		Success      bool                `json:"success"`
		Error        string              `json:"error,omitempty"`
		Deferred     bool                `json:"deferred,omitempty"`
		DeferReason  string              `json:"defer_reason,omitempty"`
		HttpStatus   int                 `json:"http_status,omitempty"`
		DesiredState *DesiredStateResult `json:"desired_state,omitempty"`
	}
	if err := json.Unmarshal(data, &a); err != nil {
		return err
	}
	m.CommandId = a.CommandId
	m.Success = a.Success
	m.Error = a.Error
	m.Deferred = a.Deferred
	m.DeferReason = a.DeferReason
	m.HttpStatus = a.HttpStatus
	switch {
	case a.DesiredState != nil:
		m.Result = &CommandResult_DesiredState{DesiredState: a.DesiredState}
	}
	return nil
}

func (m *CommandResult) GetDesiredState() *DesiredStateResult {
	if x, ok := m.Result.(*CommandResult_DesiredState); ok {
		return x.DesiredState
	}
	return nil
}

type ContentRequest struct {
	RequestId string `json:"request_id,omitempty"`
}

type ContentResponse struct {
	RequestId  string `json:"request_id,omitempty"`
	JcascYaml  string `json:"jcasc_yaml,omitempty"`
	ItemsYaml  string `json:"items_yaml,omitempty"`
	PluginsTxt string `json:"plugins_txt,omitempty"`
}

type DeferredDeletion struct {
	Path   string `json:"path,omitempty"`
	Reason string `json:"reason,omitempty"`
}

type DesiredStateCommand struct {
	CommandId                  string `json:"command_id"`
	JcascYaml                  string `json:"jcasc_yaml,omitempty"`
	RbacYaml                   string `json:"rbac_yaml,omitempty"`
	DesiredStateHash           string `json:"desired_state_hash,omitempty"`
	Reload                     bool   `json:"reload,omitempty"`
	ItemsYaml                  string `json:"items_yaml,omitempty"`
	MiteJenkinsToken           string `json:"mite_jenkins_token,omitempty"`
	MiteJenkinsTokenExp        int64  `json:"mite_jenkins_token_exp,omitempty"`
	CommandDeadlineSec         int64  `json:"command_deadline_sec,omitempty"`
	ApplyWhen                  string `json:"apply_when,omitempty"`
	MaxDeferSec                int64  `json:"max_defer_sec,omitempty"`
	DrainTimeoutSec            int64  `json:"drain_timeout_sec,omitempty"`
	LiveFingerprintIntervalSec int64  `json:"live_fingerprint_interval_sec,omitempty"`
}

type DesiredStateResult struct {
	ConfigSuccess         bool                `json:"config_success"`
	RbacSuccess           bool                `json:"rbac_success"`
	PluginsSuccess        bool                `json:"plugins_success"`
	ItemsSuccess          bool                `json:"items_success"`
	ConfigError           string              `json:"config_error,omitempty"`
	RbacError             string              `json:"rbac_error,omitempty"`
	PluginsError          string              `json:"plugins_error,omitempty"`
	ItemsError            string              `json:"items_error,omitempty"`
	AppliedHash           string              `json:"applied_hash,omitempty"`
	DeferredItemDeletions []*DeferredDeletion `json:"deferred_item_deletions,omitempty"`
}

type Heartbeat struct {
	Version              string      `json:"version"`
	ActualStateHash      string      `json:"actual_state_hash,omitempty"`
	Idle                 *IdleGauges `json:"idle,omitempty"`
	InstalledPluginsHash string      `json:"installed_plugins_hash,omitempty"`
}

type Hello struct {
	ControllerName string `json:"controller_name"`
	Namespace      string `json:"namespace"`
	Version        string `json:"version"`
}

type IdleGauges struct {
	LastHttpActivityUnix int64 `json:"last_http_activity_unix,omitempty"`
	LastEventUnix        int64 `json:"last_event_unix,omitempty"`
	RunningBuilds        int   `json:"running_builds,omitempty"`
	QueueLength          int   `json:"queue_length,omitempty"`
	TimerTriggerJobs     int   `json:"timer_trigger_jobs,omitempty"`
}

type ImperativeCommand struct {
	CommandId       string                `json:"command_id"`
	Type            CommandType           `json:"type"`
	Target          string                `json:"target,omitempty"`
	DeadlineSec     int64                 `json:"deadline_sec,omitempty"`
	DrainTimeoutSec int64                 `json:"drain_timeout_sec,omitempty"`
	ReplayWebhook   *ReplayWebhookPayload `json:"replay_webhook,omitempty"`
}

type InstalledPlugin struct {
	Name     string       `json:"name"`
	Version  string       `json:"version"`
	Enabled  string       `json:"enabled,omitempty"`
	Detached string       `json:"detached,omitempty"`
	Bundled  string       `json:"bundled,omitempty"`
	Deps     []*PluginDep `json:"deps,omitempty"`
}

type JenkinsActivityEvent struct {
	Type        string `json:"type,omitempty"`
	Actor       string `json:"actor,omitempty"`
	Message     string `json:"message,omitempty"`
	ItemPath    string `json:"item_path,omitempty"`
	BuildNumber int64  `json:"build_number,omitempty"`
	Result      string `json:"result,omitempty"`
	URL         string `json:"url,omitempty"`
	Timestamp   string `json:"timestamp,omitempty"`
}

type MiteMessage struct {
	Message isMiteMessage_message `json:"-"`
}

type isMiteMessage_message interface {
	isMiteMessage_message()
}

type MiteMessage_Hello struct {
	Hello *Hello `json:"hello,omitempty"`
}

func (*MiteMessage_Hello) isMiteMessage_message() {}

type MiteMessage_Heartbeat struct {
	Heartbeat *Heartbeat `json:"heartbeat,omitempty"`
}

func (*MiteMessage_Heartbeat) isMiteMessage_message() {}

type MiteMessage_StateSnapshot struct {
	StateSnapshot *StateSnapshot `json:"state_snapshot,omitempty"`
}

func (*MiteMessage_StateSnapshot) isMiteMessage_message() {}

type MiteMessage_CommandResult struct {
	CommandResult *CommandResult `json:"command_result,omitempty"`
}

func (*MiteMessage_CommandResult) isMiteMessage_message() {}

type MiteMessage_TokenRefreshRequest struct {
	TokenRefreshRequest *TokenRefreshRequest `json:"token_refresh_request,omitempty"`
}

func (*MiteMessage_TokenRefreshRequest) isMiteMessage_message() {}

type MiteMessage_ObservabilityReport struct {
	ObservabilityReport *ObservabilityReport `json:"observability_report,omitempty"`
}

func (*MiteMessage_ObservabilityReport) isMiteMessage_message() {}

type MiteMessage_ContentResponse struct {
	ContentResponse *ContentResponse `json:"content_response,omitempty"`
}

func (*MiteMessage_ContentResponse) isMiteMessage_message() {}

type MiteMessage_JenkinsActivity struct {
	JenkinsActivity *JenkinsActivityEvent `json:"jenkins_activity,omitempty"`
}

func (*MiteMessage_JenkinsActivity) isMiteMessage_message() {}

type MiteMessage_PluginInventory struct {
	PluginInventory *PluginInventory `json:"plugin_inventory,omitempty"`
}

func (*MiteMessage_PluginInventory) isMiteMessage_message() {}

func (m *MiteMessage) MarshalJSON() ([]byte, error) {
	type alias struct {
		Hello               *Hello                `json:"hello,omitempty"`
		Heartbeat           *Heartbeat            `json:"heartbeat,omitempty"`
		StateSnapshot       *StateSnapshot        `json:"state_snapshot,omitempty"`
		CommandResult       *CommandResult        `json:"command_result,omitempty"`
		TokenRefreshRequest *TokenRefreshRequest  `json:"token_refresh_request,omitempty"`
		ObservabilityReport *ObservabilityReport  `json:"observability_report,omitempty"`
		ContentResponse     *ContentResponse      `json:"content_response,omitempty"`
		JenkinsActivity     *JenkinsActivityEvent `json:"jenkins_activity,omitempty"`
		PluginInventory     *PluginInventory      `json:"plugin_inventory,omitempty"`
	}
	var a alias
	switch v := m.Message.(type) {
	case *MiteMessage_Hello:
		a.Hello = v.Hello
	case *MiteMessage_Heartbeat:
		a.Heartbeat = v.Heartbeat
	case *MiteMessage_StateSnapshot:
		a.StateSnapshot = v.StateSnapshot
	case *MiteMessage_CommandResult:
		a.CommandResult = v.CommandResult
	case *MiteMessage_TokenRefreshRequest:
		a.TokenRefreshRequest = v.TokenRefreshRequest
	case *MiteMessage_ObservabilityReport:
		a.ObservabilityReport = v.ObservabilityReport
	case *MiteMessage_ContentResponse:
		a.ContentResponse = v.ContentResponse
	case *MiteMessage_JenkinsActivity:
		a.JenkinsActivity = v.JenkinsActivity
	case *MiteMessage_PluginInventory:
		a.PluginInventory = v.PluginInventory
	}
	return json.Marshal(a)
}

func (m *MiteMessage) UnmarshalJSON(data []byte) error {
	var a struct {
		Hello               *Hello                `json:"hello,omitempty"`
		Heartbeat           *Heartbeat            `json:"heartbeat,omitempty"`
		StateSnapshot       *StateSnapshot        `json:"state_snapshot,omitempty"`
		CommandResult       *CommandResult        `json:"command_result,omitempty"`
		TokenRefreshRequest *TokenRefreshRequest  `json:"token_refresh_request,omitempty"`
		ObservabilityReport *ObservabilityReport  `json:"observability_report,omitempty"`
		ContentResponse     *ContentResponse      `json:"content_response,omitempty"`
		JenkinsActivity     *JenkinsActivityEvent `json:"jenkins_activity,omitempty"`
		PluginInventory     *PluginInventory      `json:"plugin_inventory,omitempty"`
	}
	if err := json.Unmarshal(data, &a); err != nil {
		return err
	}
	switch {
	case a.Hello != nil:
		m.Message = &MiteMessage_Hello{Hello: a.Hello}
	case a.Heartbeat != nil:
		m.Message = &MiteMessage_Heartbeat{Heartbeat: a.Heartbeat}
	case a.StateSnapshot != nil:
		m.Message = &MiteMessage_StateSnapshot{StateSnapshot: a.StateSnapshot}
	case a.CommandResult != nil:
		m.Message = &MiteMessage_CommandResult{CommandResult: a.CommandResult}
	case a.TokenRefreshRequest != nil:
		m.Message = &MiteMessage_TokenRefreshRequest{TokenRefreshRequest: a.TokenRefreshRequest}
	case a.ObservabilityReport != nil:
		m.Message = &MiteMessage_ObservabilityReport{ObservabilityReport: a.ObservabilityReport}
	case a.ContentResponse != nil:
		m.Message = &MiteMessage_ContentResponse{ContentResponse: a.ContentResponse}
	case a.JenkinsActivity != nil:
		m.Message = &MiteMessage_JenkinsActivity{JenkinsActivity: a.JenkinsActivity}
	case a.PluginInventory != nil:
		m.Message = &MiteMessage_PluginInventory{PluginInventory: a.PluginInventory}
	}
	return nil
}

func (m *MiteMessage) GetHello() *Hello {
	if x, ok := m.Message.(*MiteMessage_Hello); ok {
		return x.Hello
	}
	return nil
}

func (m *MiteMessage) GetHeartbeat() *Heartbeat {
	if x, ok := m.Message.(*MiteMessage_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *MiteMessage) GetStateSnapshot() *StateSnapshot {
	if x, ok := m.Message.(*MiteMessage_StateSnapshot); ok {
		return x.StateSnapshot
	}
	return nil
}

func (m *MiteMessage) GetCommandResult() *CommandResult {
	if x, ok := m.Message.(*MiteMessage_CommandResult); ok {
		return x.CommandResult
	}
	return nil
}

func (m *MiteMessage) GetTokenRefreshRequest() *TokenRefreshRequest {
	if x, ok := m.Message.(*MiteMessage_TokenRefreshRequest); ok {
		return x.TokenRefreshRequest
	}
	return nil
}

func (m *MiteMessage) GetObservabilityReport() *ObservabilityReport {
	if x, ok := m.Message.(*MiteMessage_ObservabilityReport); ok {
		return x.ObservabilityReport
	}
	return nil
}

func (m *MiteMessage) GetContentResponse() *ContentResponse {
	if x, ok := m.Message.(*MiteMessage_ContentResponse); ok {
		return x.ContentResponse
	}
	return nil
}

func (m *MiteMessage) GetJenkinsActivity() *JenkinsActivityEvent {
	if x, ok := m.Message.(*MiteMessage_JenkinsActivity); ok {
		return x.JenkinsActivity
	}
	return nil
}

func (m *MiteMessage) GetPluginInventory() *PluginInventory {
	if x, ok := m.Message.(*MiteMessage_PluginInventory); ok {
		return x.PluginInventory
	}
	return nil
}

type ObservabilityBuild struct {
	JobName         string `json:"job_name"`
	BuildNumber     int    `json:"build_number"`
	Status          string `json:"status"`
	StartedAt       string `json:"started_at,omitempty"`
	DurationSeconds int    `json:"duration_seconds,omitempty"`
	URL             string `json:"url,omitempty"`
}

type ObservabilityReport struct {
	ObservedAt   string                `json:"observed_at"`
	Sources      []*ObservableSource   `json:"sources,omitempty"`
	Capabilities []string              `json:"capabilities,omitempty"`
	Summary      *ObservabilitySummary `json:"summary,omitempty"`
	TTLSeconds   int                   `json:"ttl_seconds"`
}

type ObservabilitySummary struct {
	TotalJobs     int                   `json:"total_jobs,omitempty"`
	RunningBuilds int                   `json:"running_builds,omitempty"`
	RecentBuilds  []*ObservabilityBuild `json:"recent_builds,omitempty"`
}

type ObservableSource struct {
	Provider string            `json:"provider"`
	Status   string            `json:"status"`
	Error    string            `json:"error,omitempty"`
	Hints    map[string]string `json:"hints,omitempty"`
}

type OperatorMessage struct {
	Message isOperatorMessage_message `json:"-"`
}

type isOperatorMessage_message interface {
	isOperatorMessage_message()
}

type OperatorMessage_DesiredState struct {
	DesiredState *DesiredStateCommand `json:"desired_state,omitempty"`
}

func (*OperatorMessage_DesiredState) isOperatorMessage_message() {}

type OperatorMessage_Imperative struct {
	Imperative *ImperativeCommand `json:"imperative,omitempty"`
}

func (*OperatorMessage_Imperative) isOperatorMessage_message() {}

type OperatorMessage_TokenGrant struct {
	TokenGrant *TokenGrant `json:"token_grant,omitempty"`
}

func (*OperatorMessage_TokenGrant) isOperatorMessage_message() {}

type OperatorMessage_ContentRequest struct {
	ContentRequest *ContentRequest `json:"content_request,omitempty"`
}

func (*OperatorMessage_ContentRequest) isOperatorMessage_message() {}

func (m *OperatorMessage) MarshalJSON() ([]byte, error) {
	type alias struct {
		DesiredState   *DesiredStateCommand `json:"desired_state,omitempty"`
		Imperative     *ImperativeCommand   `json:"imperative,omitempty"`
		TokenGrant     *TokenGrant          `json:"token_grant,omitempty"`
		ContentRequest *ContentRequest      `json:"content_request,omitempty"`
	}
	var a alias
	switch v := m.Message.(type) {
	case *OperatorMessage_DesiredState:
		a.DesiredState = v.DesiredState
	case *OperatorMessage_Imperative:
		a.Imperative = v.Imperative
	case *OperatorMessage_TokenGrant:
		a.TokenGrant = v.TokenGrant
	case *OperatorMessage_ContentRequest:
		a.ContentRequest = v.ContentRequest
	}
	return json.Marshal(a)
}

func (m *OperatorMessage) UnmarshalJSON(data []byte) error {
	var a struct {
		DesiredState   *DesiredStateCommand `json:"desired_state,omitempty"`
		Imperative     *ImperativeCommand   `json:"imperative,omitempty"`
		TokenGrant     *TokenGrant          `json:"token_grant,omitempty"`
		ContentRequest *ContentRequest      `json:"content_request,omitempty"`
	}
	if err := json.Unmarshal(data, &a); err != nil {
		return err
	}
	switch {
	case a.DesiredState != nil:
		m.Message = &OperatorMessage_DesiredState{DesiredState: a.DesiredState}
	case a.Imperative != nil:
		m.Message = &OperatorMessage_Imperative{Imperative: a.Imperative}
	case a.TokenGrant != nil:
		m.Message = &OperatorMessage_TokenGrant{TokenGrant: a.TokenGrant}
	case a.ContentRequest != nil:
		m.Message = &OperatorMessage_ContentRequest{ContentRequest: a.ContentRequest}
	}
	return nil
}

func (m *OperatorMessage) GetDesiredState() *DesiredStateCommand {
	if x, ok := m.Message.(*OperatorMessage_DesiredState); ok {
		return x.DesiredState
	}
	return nil
}

func (m *OperatorMessage) GetImperative() *ImperativeCommand {
	if x, ok := m.Message.(*OperatorMessage_Imperative); ok {
		return x.Imperative
	}
	return nil
}

func (m *OperatorMessage) GetTokenGrant() *TokenGrant {
	if x, ok := m.Message.(*OperatorMessage_TokenGrant); ok {
		return x.TokenGrant
	}
	return nil
}

func (m *OperatorMessage) GetContentRequest() *ContentRequest {
	if x, ok := m.Message.(*OperatorMessage_ContentRequest); ok {
		return x.ContentRequest
	}
	return nil
}

type PluginDep struct {
	Name     string `json:"name"`
	Min      string `json:"min,omitempty"`
	Optional bool   `json:"optional,omitempty"`
}

type PluginInventory struct {
	InstalledPluginsHash string             `json:"installed_plugins_hash"`
	CollectedAt          string             `json:"collected_at,omitempty"`
	Source               string             `json:"source,omitempty"`
	Plugins              []*InstalledPlugin `json:"plugins,omitempty"`
	Degraded             bool               `json:"degraded,omitempty"`
	Truncated            bool               `json:"truncated,omitempty"`
	CollectionFailed     bool               `json:"collection_failed,omitempty"`
	CollectionError      string             `json:"collection_error,omitempty"`
	OptionalEdgesDropped bool               `json:"optional_edges_dropped,omitempty"`
	AllEdgesDropped      bool               `json:"all_edges_dropped,omitempty"`
	Warnings             []string           `json:"warnings,omitempty"`
}

type RegisterRequest struct {
	ControllerName string `json:"controller_name"`
	Namespace      string `json:"namespace"`
	BootstrapToken string `json:"bootstrap_token,omitempty"`
	PublicKey      []byte `json:"public_key,omitempty"`
}

type RegisterResponse struct {
	CertificatePem string `json:"certificate_pem"`
	CaPem          string `json:"ca_pem"`
	ServerEndpoint string `json:"server_endpoint"`
}

type ReplayWebhookPayload struct {
	Path       string            `json:"path,omitempty"`
	Query      string            `json:"query,omitempty"`
	Headers    map[string]string `json:"headers,omitempty"`
	Body       []byte            `json:"body,omitempty"`
	DeliveryId string            `json:"delivery_id,omitempty"`
}

type StateSnapshot struct {
	ActualStateHash string `json:"actual_state_hash,omitempty"`
	ConfigHash      string `json:"config_hash,omitempty"`
	PluginsHash     string `json:"plugins_hash,omitempty"`
	RbacHash        string `json:"rbac_hash,omitempty"`
	JenkinsVersion  string `json:"jenkins_version,omitempty"`
	Status          string `json:"status,omitempty"`
	JenkinsHealth   string `json:"jenkins_health,omitempty"`
	ItemsHash       string `json:"items_hash,omitempty"`
	ApplyDeferred   bool   `json:"apply_deferred,omitempty"`
	DeferReason     string `json:"defer_reason,omitempty"`
	LiveConfigHash  string `json:"live_config_hash,omitempty"`
	LiveDrift       bool   `json:"live_drift,omitempty"`
}

type TokenGrant struct {
	MiteJenkinsToken    string `json:"mite_jenkins_token,omitempty"`
	MiteJenkinsTokenExp int64  `json:"mite_jenkins_token_exp,omitempty"`
}

type TokenRefreshRequest struct {
}

type CommandType int32

const (
	CommandTypeUnspecified            CommandType = 0
	CommandTypeSafeRestart            CommandType = 1
	CommandTypeDeleteItem             CommandType = 2
	CommandTypeReplayWebhook          CommandType = 3
	CommandTypeCollectPluginInventory CommandType = 4
)

// MiteServer is the server-side interface for the Mite service.
type MiteServer interface {
	Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error)
	CommandStream(stream Mite_CommandStreamServer) error
}

// Mite_CommandStreamServer is the server-side streaming interface.
type Mite_CommandStreamServer interface {
	grpc.ServerStream
	Send(*OperatorMessage) error
	Recv() (*MiteMessage, error)
}

// MiteClient is the client-side interface for the Mite service.
type MiteClient interface {
	Register(ctx context.Context, req *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	CommandStream(ctx context.Context, opts ...grpc.CallOption) (Mite_CommandStreamClient, error)
}

// Mite_CommandStreamClient is the client-side streaming interface.
type Mite_CommandStreamClient interface {
	grpc.ClientStream
	Send(*MiteMessage) error
	Recv() (*OperatorMessage, error)
}

// NewMiteClient creates a new Mite client.
func NewMiteClient(cc *grpc.ClientConn) MiteClient {
	return &miteClient{cc: cc}
}

type miteClient struct {
	cc *grpc.ClientConn
}

func (c *miteClient) Register(ctx context.Context, req *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/mitev1.Mite/Register", req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}
func (c *miteClient) CommandStream(ctx context.Context, opts ...grpc.CallOption) (Mite_CommandStreamClient, error) {
	desc := &grpc.StreamDesc{
		StreamName:    "CommandStream",
		ServerStreams: true,
		ClientStreams: true,
	}
	stream, err := c.cc.NewStream(ctx, desc, "/mitev1.Mite/CommandStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &miteCommandStreamClient{ClientStream: stream}
	return x, nil
}

type miteCommandStreamClient struct {
	grpc.ClientStream
}

func (x *miteCommandStreamClient) Send(m *MiteMessage) error {
	return x.ClientStream.SendMsg(m)
}
func (x *miteCommandStreamClient) Recv() (*OperatorMessage, error) {
	m := new(OperatorMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UnimplementedMiteServer provides default unimplemented methods.
type UnimplementedMiteServer struct{}

func (UnimplementedMiteServer) Register(ctx context.Context, _ *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "unimplemented")
}

func (UnimplementedMiteServer) CommandStream(_ Mite_CommandStreamServer) error {
	return status.Error(codes.Unimplemented, "unimplemented")
}

// RegisterMiteServer registers the Mite service implementation with a gRPC server.
func RegisterMiteServer(s *grpc.Server, srv MiteServer) {
	s.RegisterService(&Mite_ServiceDesc, srv)
}

// Mite_ServiceDesc is the grpc.ServiceDesc for the Mite service.
var Mite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mitev1.Mite",
	HandlerType: (*MiteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Mite_Register_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CommandStream",
			Handler:       _Mite_CommandStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

func _Mite_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiteServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mitev1.Mite/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiteServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}
func _Mite_CommandStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MiteServer).CommandStream(&miteCommandStreamServer{stream})
}

type miteCommandStreamServer struct {
	grpc.ServerStream
}

func (x *miteCommandStreamServer) Send(m *OperatorMessage) error {
	return x.ServerStream.SendMsg(m)
}
func (x *miteCommandStreamServer) Recv() (*MiteMessage, error) {
	m := new(MiteMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}
