{{- if not (include "varroa.isHive" .) }}
{{- if .Values.grafana.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "varroa.fullname" (dict "Release" .Release "name" "grafana-datasources") }}
  labels:
    app.kubernetes.io/component: grafana
    {{- include "varroa.labels" . | nindent 4 }}
type: Opaque
stringData:
  datasources.yaml: |
    {{- toYaml .Values.grafana.datasources | nindent 4 }}
{{- end }}

{{- end }}
