{{- if .Values.gateway.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "varroa.fullname" (dict "Release" .Release "name" "varroa-gateway") }}
  labels:
    app.kubernetes.io/component: varroa-gateway
    {{- include "varroa.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "varroa.fullname" (dict "Release" .Release "name" "varroa-gateway") }}
subjects:
  - kind: ServiceAccount
    name: {{ include "varroa.fullname" (dict "Release" .Release "name" "varroa-gateway") }}
    namespace: {{ .Release.Namespace }}
{{- end }}
