import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import fixture from "./__fixtures__/openapi.json";
import { getControllerSpecSchema } from "./openapiSchema";

// The BFF's canonical bundled OpenAPI document (generated by hack/openapi-bundle).
// This test file lives at frontend/src/api/, so ../../../ from here is the repo root.
const canonical = JSON.parse(
  readFileSync(join(import.meta.dirname, "../../../api/openapi/varroa.json"), "utf8"),
);

// The fixture is a curated, ref-inlined mirror of the schemas the UI renders,
// and its ControllerSpec is regenerated from canonical by
// frontend/scripts/sync-openapi-fixture.mjs. If it drifts — e.g. a resource
// quantity pattern is added to the contract but not to the fixture — the whole
// schema diverges and this test fails, so the suite cannot pass against a
// stale contract.
describe("openapi fixture mirrors the canonical ControllerSpec", () => {
  it("resolves the same ControllerSpec schema as the bundled document", () => {
    expect(getControllerSpecSchema(fixture)).toEqual(getControllerSpecSchema(canonical));
  });

  it("carries the resource limits/requests properties (the historical staleness)", () => {
    const schema = getControllerSpecSchema(fixture);
    const resources = (schema as Record<string, any>)?.properties?.resources as
      | { properties?: Record<string, unknown> }
      | undefined;
    expect(resources?.properties).toHaveProperty("limits");
    expect(resources?.properties).toHaveProperty("requests");
  });
});
