{{- if and .Values.updateCenter.enabled (not (include "varroa.isHive" .)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: varroa-updatecenter
  labels:
    app.kubernetes.io/component: varroa-updatecenter
    {{- include "varroa.labels" . | nindent 4 }}
{{- end }}
