// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another object.
func (in *Controller) DeepCopyInto(out *Controller) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of Controller.
func (in *Controller) DeepCopy() *Controller {
	if in == nil {
		return nil
	}
	out := new(Controller)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Controller) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another ControllerList.
func (in *ControllerList) DeepCopyInto(out *ControllerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Controller, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ControllerList.
func (in *ControllerList) DeepCopy() *ControllerList {
	if in == nil {
		return nil
	}
	out := new(ControllerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ControllerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for ControllerSpec.
func (in *ControllerSpec) DeepCopyInto(out *ControllerSpec) {
	*out = *in
	if in.PluginSpec != nil {
		in, out := &in.PluginSpec, &out.PluginSpec
		*out = new(PluginSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.BackupSpec != nil {
		in, out := &in.BackupSpec, &out.BackupSpec
		*out = new(BackupSpec)
		**out = **in
	}
	if in.IngressSpec != nil {
		in, out := &in.IngressSpec, &out.IngressSpec
		*out = new(IngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.MiteSpec != nil {
		in, out := &in.MiteSpec, &out.MiteSpec
		*out = new(MiteSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(PersistenceSpec)
		**out = **in
	}
	if in.ReconciliationPolicy != nil {
		in, out := &in.ReconciliationPolicy, &out.ReconciliationPolicy
		*out = new(ReconciliationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.ComposedBundleRef != nil {
		in, out := &in.ComposedBundleRef, &out.ComposedBundleRef
		*out = new(ComposedBundleRef)
		**out = **in
	}
	if in.RBACSpec != nil {
		in, out := &in.RBACSpec, &out.RBACSpec
		*out = new(RBACSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PodOverrides != nil {
		in, out := &in.PodOverrides, &out.PodOverrides
		*out = new(PodOverrides)
		(*in).DeepCopyInto(*out)
	}
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = new(ProbesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceOverlay != nil {
		in, out := &in.ResourceOverlay, &out.ResourceOverlay
		*out = new(ResourceOverlay)
		**out = **in
	}
	if in.Hibernation != nil {
		in, out := &in.Hibernation, &out.Hibernation
		*out = new(HibernationSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto for ProbesSpec.
func (in *ProbesSpec) DeepCopyInto(out *ProbesSpec) {
	*out = *in
	if in.Startup != nil {
		in, out := &in.Startup, &out.Startup
		*out = new(ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(ProbeSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of ProbesSpec.
func (in *ProbesSpec) DeepCopy() *ProbesSpec {
	if in == nil {
		return nil
	}
	out := new(ProbesSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ProbeSpec.
func (in *ProbeSpec) DeepCopyInto(out *ProbeSpec) {
	*out = *in
	if in.InitialDelaySeconds != nil {
		in, out := &in.InitialDelaySeconds, &out.InitialDelaySeconds
		*out = new(int32)
		**out = **in
	}
	if in.PeriodSeconds != nil {
		in, out := &in.PeriodSeconds, &out.PeriodSeconds
		*out = new(int32)
		**out = **in
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	if in.FailureThreshold != nil {
		in, out := &in.FailureThreshold, &out.FailureThreshold
		*out = new(int32)
		**out = **in
	}
	if in.SuccessThreshold != nil {
		in, out := &in.SuccessThreshold, &out.SuccessThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy creates a deep copy of ProbeSpec.
func (in *ProbeSpec) DeepCopy() *ProbeSpec {
	if in == nil {
		return nil
	}
	out := new(ProbeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for IngressSpec.
func (in *IngressSpec) DeepCopyInto(out *IngressSpec) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy creates a deep copy of IngressSpec.
func (in *IngressSpec) DeepCopy() *IngressSpec {
	if in == nil {
		return nil
	}
	out := new(IngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for PluginSpec.
func (in *PluginSpec) DeepCopyInto(out *PluginSpec) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]PluginEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for PersistenceSpec.
func (in *PersistenceSpec) DeepCopyInto(out *PersistenceSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of PersistenceSpec.
func (in *PersistenceSpec) DeepCopy() *PersistenceSpec {
	if in == nil {
		return nil
	}
	out := new(PersistenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for MiteSpec.
func (in *MiteSpec) DeepCopyInto(out *MiteSpec) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto for ControllerStatus.
func (in *ControllerStatus) DeepCopyInto(out *ControllerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ControllerCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ProvisioningStartedAt != nil {
		in, out := &in.ProvisioningStartedAt, &out.ProvisioningStartedAt
		*out = (*in).DeepCopy()
	}
	if in.MiteStatus != nil {
		in, out := &in.MiteStatus, &out.MiteStatus
		*out = new(MiteStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.FirstConnectedAt != nil {
		in, out := &in.FirstConnectedAt, &out.FirstConnectedAt
		*out = (*in).DeepCopy()
	}
	if in.PendingRestart != nil {
		in, out := &in.PendingRestart, &out.PendingRestart
		*out = new(PendingRestart)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingPluginRoll != nil {
		in, out := &in.PendingPluginRoll, &out.PendingPluginRoll
		*out = new(PendingPluginRoll)
		(*in).DeepCopyInto(*out)
	}
	if in.PendingItemDeletions != nil {
		in, out := &in.PendingItemDeletions, &out.PendingItemDeletions
		*out = make([]PendingDeletion, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RestartDrain != nil {
		in, out := &in.RestartDrain, &out.RestartDrain
		*out = new(RestartDrainStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastImperativeResult != nil {
		in, out := &in.LastImperativeResult, &out.LastImperativeResult
		*out = new(ImperativeResult)
		(*in).DeepCopyInto(*out)
	}
	if in.LiveDrift != nil {
		in, out := &in.LiveDrift, &out.LiveDrift
		*out = new(LiveDriftStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Rollout != nil {
		in, out := &in.Rollout, &out.Rollout
		*out = new(RolloutStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LastReconciledAt != nil {
		in, out := &in.LastReconciledAt, &out.LastReconciledAt
		*out = (*in).DeepCopy()
	}
	if in.LastDesiredPushAt != nil {
		in, out := &in.LastDesiredPushAt, &out.LastDesiredPushAt
		*out = (*in).DeepCopy()
	}
	if in.LastReconcileErrorAt != nil {
		in, out := &in.LastReconcileErrorAt, &out.LastReconcileErrorAt
		*out = (*in).DeepCopy()
	}
	if in.LastApplyResult != nil {
		in, out := &in.LastApplyResult, &out.LastApplyResult
		*out = new(ApplyResult)
		(*in).DeepCopyInto(*out)
	}
	if in.ApplyHistory != nil {
		in, out := &in.ApplyHistory, &out.ApplyHistory
		*out = make([]ApplyResult, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.OverlayWarnings != nil {
		in, out := &in.OverlayWarnings, &out.OverlayWarnings
		*out = make([]OverlayWarning, len(*in))
		copy(*out, *in)
	}
	if in.LastActivityAt != nil {
		in, out := &in.LastActivityAt, &out.LastActivityAt
		*out = (*in).DeepCopy()
	}
	if in.HibernatedAt != nil {
		in, out := &in.HibernatedAt, &out.HibernatedAt
		*out = (*in).DeepCopy()
	}
	if in.PluginInventory != nil {
		in, out := &in.PluginInventory, &out.PluginInventory
		*out = new(PluginInventoryStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto for ApplySectionResult.
func (in *ApplySectionResult) DeepCopyInto(out *ApplySectionResult) {
	*out = *in
}

// DeepCopy creates a deep copy of ApplySectionResult.
func (in *ApplySectionResult) DeepCopy() *ApplySectionResult {
	if in == nil {
		return nil
	}
	out := new(ApplySectionResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ApplyResult.
func (in *ApplyResult) DeepCopyInto(out *ApplyResult) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
	if in.Sections != nil {
		in, out := &in.Sections, &out.Sections
		*out = make([]ApplySectionResult, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for ControllerCondition.
func (in *ControllerCondition) DeepCopyInto(out *ControllerCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopyInto for MiteStatus.
func (in *MiteStatus) DeepCopyInto(out *MiteStatus) {
	*out = *in
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
	if in.CertExpiry != nil {
		in, out := &in.CertExpiry, &out.CertExpiry
		*out = (*in).DeepCopy()
	}
}

// DeepCopyInto for User.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy for User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *User) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for UserList.
func (in *UserList) DeepCopyInto(out *UserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for UserList.
func (in *UserList) DeepCopy() *UserList {
	if in == nil {
		return nil
	}
	out := new(UserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *UserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for UserSpec.
func (in *UserSpec) DeepCopyInto(out *UserSpec) {
	*out = *in
}

// DeepCopyInto for UserPreferences.
func (in *UserPreferences) DeepCopyInto(out *UserPreferences) {
	*out = *in
}

// DeepCopyInto for UserCredentials.
func (in *UserCredentials) DeepCopyInto(out *UserCredentials) {
	*out = *in
	if in.LastChanged != nil {
		in, out := &in.LastChanged, &out.LastChanged
		*out = (*in).DeepCopy()
	}
}

// DeepCopyInto for UserStatus.
func (in *UserStatus) DeepCopyInto(out *UserStatus) {
	*out = *in
	if in.LastLogin != nil {
		in, out := &in.LastLogin, &out.LastLogin
		*out = (*in).DeepCopy()
	}
	if in.ActiveControllers != nil {
		in, out := &in.ActiveControllers, &out.ActiveControllers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Preferences != nil {
		in, out := &in.Preferences, &out.Preferences
		*out = new(UserPreferences)
		(*in).DeepCopyInto(*out)
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(UserCredentials)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservedGroups != nil {
		in, out := &in.ObservedGroups, &out.ObservedGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for Group.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy creates a deep copy of Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Group) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for GroupList.
func (in *GroupList) DeepCopyInto(out *GroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Group, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of GroupList.
func (in *GroupList) DeepCopy() *GroupList {
	if in == nil {
		return nil
	}
	out := new(GroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *GroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for GroupSpec.
func (in *GroupSpec) DeepCopyInto(out *GroupSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for GroupStatus.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	*out = *in
}

// DeepCopyInto for Team.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for TeamList.
func (in *TeamList) DeepCopyInto(out *TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of TeamList.
func (in *TeamList) DeepCopy() *TeamList {
	if in == nil {
		return nil
	}
	out := new(TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for TeamSpec.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	if in.Members != nil {
		in, out := &in.Members, &out.Members
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]SubjectRef, len(*in))
		copy(*out, *in)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for TeamStatus.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	if in.NamespaceStates != nil {
		in, out := &in.NamespaceStates, &out.NamespaceStates
		*out = make([]TeamNamespaceState, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TeamCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto for TeamNamespaceState.
func (in *TeamNamespaceState) DeepCopyInto(out *TeamNamespaceState) {
	*out = *in
}

// DeepCopyInto for TeamCondition.
func (in *TeamCondition) DeepCopyInto(out *TeamCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopyInto for PodTemplate.
func (in *PodTemplate) DeepCopyInto(out *PodTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy for PodTemplate.
func (in *PodTemplate) DeepCopy() *PodTemplate {
	if in == nil {
		return nil
	}
	out := new(PodTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PodTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for PodTemplateList.
func (in *PodTemplateList) DeepCopyInto(out *PodTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PodTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for PodTemplateList.
func (in *PodTemplateList) DeepCopy() *PodTemplateList {
	if in == nil {
		return nil
	}
	out := new(PodTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *PodTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for PodTemplateSpec.
func (in *PodTemplateSpec) DeepCopyInto(out *PodTemplateSpec) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopyInto for ContainerSpec.
func (in *ContainerSpec) DeepCopyInto(out *ContainerSpec) {
	*out = *in
	if in.Command != nil {
		in, out := &in.Command, &out.Command
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopyInto for BuildMetric.
func (in *BuildMetric) DeepCopyInto(out *BuildMetric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy for BuildMetric.
func (in *BuildMetric) DeepCopy() *BuildMetric {
	if in == nil {
		return nil
	}
	out := new(BuildMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *BuildMetric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for BuildMetricList.
func (in *BuildMetricList) DeepCopyInto(out *BuildMetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BuildMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy for BuildMetricList.
func (in *BuildMetricList) DeepCopy() *BuildMetricList {
	if in == nil {
		return nil
	}
	out := new(BuildMetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *BuildMetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for ProvisioningDefaults.
func (in *ProvisioningDefaults) DeepCopyInto(out *ProvisioningDefaults) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ProvisioningDefaults) DeepCopy() *ProvisioningDefaults {
	if in == nil {
		return nil
	}
	out := new(ProvisioningDefaults)
	in.DeepCopyInto(out)
	return out
}

func (in *ProvisioningDefaults) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for ProvisioningDefaultsList.
func (in *ProvisioningDefaultsList) DeepCopyInto(out *ProvisioningDefaultsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProvisioningDefaults, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ProvisioningDefaultsList) DeepCopy() *ProvisioningDefaultsList {
	if in == nil {
		return nil
	}
	out := new(ProvisioningDefaultsList)
	in.DeepCopyInto(out)
	return out
}

func (in *ProvisioningDefaultsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for ProvisioningDefaultsSpec.
func (in *ProvisioningDefaultsSpec) DeepCopyInto(out *ProvisioningDefaultsSpec) {
	*out = *in
	if in.IngressAnnotations != nil {
		in, out := &in.IngressAnnotations, &out.IngressAnnotations
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.DefaultPlugins != nil {
		in, out := &in.DefaultPlugins, &out.DefaultPlugins
		*out = make([]PluginEntry, len(*in))
		copy(*out, *in)
	}
	if in.DefaultReconciliationPolicy != nil {
		in, out := &in.DefaultReconciliationPolicy, &out.DefaultReconciliationPolicy
		*out = new(ReconciliationPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SizePresets != nil {
		in, out := &in.SizePresets, &out.SizePresets
		*out = make([]SizePreset, len(*in))
		copy(*out, *in)
	}
	if in.BroodPolicy != nil {
		in, out := &in.BroodPolicy, &out.BroodPolicy
		*out = new(BroodPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto for BroodPolicy.
func (in *BroodPolicy) DeepCopyInto(out *BroodPolicy) {
	*out = *in
	if in.ExecuteGroovy != nil {
		in, out := &in.ExecuteGroovy, &out.ExecuteGroovy
		*out = new(ExecuteGroovyPolicy)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy for BroodPolicy.
func (in *BroodPolicy) DeepCopy() *BroodPolicy {
	if in == nil {
		return nil
	}
	out := new(BroodPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ExecuteGroovyPolicy.
func (in *ExecuteGroovyPolicy) DeepCopyInto(out *ExecuteGroovyPolicy) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.AllowedNamespaces != nil {
		in, out := &in.AllowedNamespaces, &out.AllowedNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy for ExecuteGroovyPolicy.
func (in *ExecuteGroovyPolicy) DeepCopy() *ExecuteGroovyPolicy {
	if in == nil {
		return nil
	}
	out := new(ExecuteGroovyPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ProvisioningDefaultsStatus.
func (in *ProvisioningDefaultsStatus) DeepCopyInto(out *ProvisioningDefaultsStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ProvisioningDefaultsCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto for ProvisioningDefaultsCondition.
func (in *ProvisioningDefaultsCondition) DeepCopyInto(out *ProvisioningDefaultsCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// DeepCopyInto for ReconciliationPolicy.
func (in *ReconciliationPolicy) DeepCopyInto(out *ReconciliationPolicy) {
	*out = *in
	if in.Interval != nil {
		in, out := &in.Interval, &out.Interval
		*out = new(metav1.Duration)
		**out = **in
	}
}

// DeepCopyInto for PendingPluginRoll.
func (in *PendingPluginRoll) DeepCopyInto(out *PendingPluginRoll) {
	*out = *in
	in.Since.DeepCopyInto(&out.Since)
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of PendingPluginRoll.
func (in *PendingPluginRoll) DeepCopy() *PendingPluginRoll {
	if in == nil {
		return nil
	}
	out := new(PendingPluginRoll)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for PendingRestart.
func (in *PendingRestart) DeepCopyInto(out *PendingRestart) {
	*out = *in
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
	if in.Changes != nil {
		in, out := &in.Changes, &out.Changes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for PendingDeletion.
func (in *PendingDeletion) DeepCopyInto(out *PendingDeletion) {
	*out = *in
	in.DetectedAt.DeepCopyInto(&out.DetectedAt)
}

// DeepCopyInto for RestartDrainStatus.
func (in *RestartDrainStatus) DeepCopyInto(out *RestartDrainStatus) {
	*out = *in
	if in.NextRetryAt != nil {
		in, out := &in.NextRetryAt, &out.NextRetryAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy creates a deep copy of RestartDrainStatus.
func (in *RestartDrainStatus) DeepCopy() *RestartDrainStatus {
	if in == nil {
		return nil
	}
	out := new(RestartDrainStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for LiveDriftStatus.
func (in *LiveDriftStatus) DeepCopyInto(out *LiveDriftStatus) {
	*out = *in
	if in.DetectedAt != nil {
		in, out := &in.DetectedAt, &out.DetectedAt
		*out = (*in).DeepCopy()
	}
	if in.LastCheckedAt != nil {
		in, out := &in.LastCheckedAt, &out.LastCheckedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy creates a deep copy of LiveDriftStatus.
func (in *LiveDriftStatus) DeepCopy() *LiveDriftStatus {
	if in == nil {
		return nil
	}
	out := new(LiveDriftStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for RolloutStatus.
func (in *RolloutStatus) DeepCopyInto(out *RolloutStatus) {
	*out = *in
	if in.WaitingOn != nil {
		in, out := &in.WaitingOn, &out.WaitingOn
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.BlockedSince != nil {
		in, out := &in.BlockedSince, &out.BlockedSince
		*out = (*in).DeepCopy()
	}
}

// DeepCopy creates a deep copy of RolloutStatus.
func (in *RolloutStatus) DeepCopy() *RolloutStatus {
	if in == nil {
		return nil
	}
	out := new(RolloutStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopy creates a deep copy of PendingDeletion.
func (in *PendingDeletion) DeepCopy() *PendingDeletion {
	if in == nil {
		return nil
	}
	out := new(PendingDeletion)
	in.DeepCopyInto(out)
	return out
}

func (in *VarroaRole) DeepCopyInto(out *VarroaRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *VarroaRole) DeepCopy() *VarroaRole {
	if in == nil {
		return nil
	}
	out := new(VarroaRole)
	in.DeepCopyInto(out)
	return out
}

func (in *VarroaRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VarroaRoleList) DeepCopyInto(out *VarroaRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VarroaRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VarroaRoleList) DeepCopy() *VarroaRoleList {
	if in == nil {
		return nil
	}
	out := new(VarroaRoleList)
	in.DeepCopyInto(out)
	return out
}

func (in *VarroaRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VarroaRoleSpec) DeepCopyInto(out *VarroaRoleSpec) {
	*out = *in
	if in.APIRules != nil {
		in, out := &in.APIRules, &out.APIRules
		*out = make([]APIRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.JenkinsPermissions != nil {
		in, out := &in.JenkinsPermissions, &out.JenkinsPermissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *APIRule) DeepCopyInto(out *APIRule) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Verbs != nil {
		in, out := &in.Verbs, &out.Verbs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *VarroaRoleBinding) DeepCopyInto(out *VarroaRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *VarroaRoleBinding) DeepCopy() *VarroaRoleBinding {
	if in == nil {
		return nil
	}
	out := new(VarroaRoleBinding)
	in.DeepCopyInto(out)
	return out
}

func (in *VarroaRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VarroaRoleBindingList) DeepCopyInto(out *VarroaRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VarroaRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *VarroaRoleBindingList) DeepCopy() *VarroaRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(VarroaRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

func (in *VarroaRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *VarroaRoleBindingSpec) DeepCopyInto(out *VarroaRoleBindingSpec) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]SubjectRef, len(*in))
		copy(*out, *in)
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(VarroaRoleBindingScope)
		(*in).DeepCopyInto(*out)
	}
}

func (in *SubjectRef) DeepCopyInto(out *SubjectRef) {
	*out = *in
}

func (in *VarroaRoleBindingScope) DeepCopyInto(out *VarroaRoleBindingScope) {
	*out = *in
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ControllerSelector != nil {
		in, out := &in.ControllerSelector, &out.ControllerSelector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
}

// JenkinsRole

func (in *JenkinsRole) DeepCopyInto(out *JenkinsRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *JenkinsRole) DeepCopy() *JenkinsRole {
	if in == nil {
		return nil
	}
	out := new(JenkinsRole)
	in.DeepCopyInto(out)
	return out
}

func (in *JenkinsRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *JenkinsRoleList) DeepCopyInto(out *JenkinsRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JenkinsRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *JenkinsRoleList) DeepCopy() *JenkinsRoleList {
	if in == nil {
		return nil
	}
	out := new(JenkinsRoleList)
	in.DeepCopyInto(out)
	return out
}

func (in *JenkinsRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *JenkinsRoleSpec) DeepCopyInto(out *JenkinsRoleSpec) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// JenkinsRoleBinding

func (in *JenkinsRoleBinding) DeepCopyInto(out *JenkinsRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

func (in *JenkinsRoleBinding) DeepCopy() *JenkinsRoleBinding {
	if in == nil {
		return nil
	}
	out := new(JenkinsRoleBinding)
	in.DeepCopyInto(out)
	return out
}

func (in *JenkinsRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *JenkinsRoleBindingList) DeepCopyInto(out *JenkinsRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JenkinsRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *JenkinsRoleBindingList) DeepCopy() *JenkinsRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(JenkinsRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

func (in *JenkinsRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *JenkinsRoleBindingSpec) DeepCopyInto(out *JenkinsRoleBindingSpec) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]SubjectRef, len(*in))
		copy(*out, *in)
	}
	if in.ControllerScope != nil {
		in, out := &in.ControllerScope, &out.ControllerScope
		*out = new(VarroaRoleBindingScope)
		(*in).DeepCopyInto(*out)
	}
	if in.JenkinsScope != nil {
		in, out := &in.JenkinsScope, &out.JenkinsScope
		*out = new(JenkinsScope)
		**out = **in
	}
}

func (in *JenkinsScope) DeepCopyInto(out *JenkinsScope) {
	*out = *in
}

// ---- CatalogSource ----

func (in *TemplateCatalogCondition) DeepCopyInto(out *TemplateCatalogCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

func (in *CatalogSource) DeepCopyInto(out *CatalogSource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *CatalogSource) DeepCopy() *CatalogSource {
	if in == nil {
		return nil
	}
	out := new(CatalogSource)
	in.DeepCopyInto(out)
	return out
}

func (in *CatalogSource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CatalogSourceList) DeepCopyInto(out *CatalogSourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CatalogSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *CatalogSourceList) DeepCopy() *CatalogSourceList {
	if in == nil {
		return nil
	}
	out := new(CatalogSourceList)
	in.DeepCopyInto(out)
	return out
}

func (in *CatalogSourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CatalogSourceSpec) DeepCopyInto(out *CatalogSourceSpec) {
	*out = *in
}

func (in *CatalogSourceStatus) DeepCopyInto(out *CatalogSourceStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TemplateCatalogCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// ---- CatalogItem ----

func (in *CatalogItem) DeepCopyInto(out *CatalogItem) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *CatalogItem) DeepCopy() *CatalogItem {
	if in == nil {
		return nil
	}
	out := new(CatalogItem)
	in.DeepCopyInto(out)
	return out
}

func (in *CatalogItem) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CatalogItemList) DeepCopyInto(out *CatalogItemList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CatalogItem, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *CatalogItemList) DeepCopy() *CatalogItemList {
	if in == nil {
		return nil
	}
	out := new(CatalogItemList)
	in.DeepCopyInto(out)
	return out
}

func (in *CatalogItemList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *CatalogItemSpec) DeepCopyInto(out *CatalogItemSpec) {
	*out = *in
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make([]CatalogVariable, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Requires != nil {
		in, out := &in.Requires, &out.Requires
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *CatalogItemStatus) DeepCopyInto(out *CatalogItemStatus) {
	*out = *in
	if in.Closure != nil {
		in, out := &in.Closure, &out.Closure
		*out = make([]CatalogItemClosureEntry, len(*in))
		copy(*out, *in)
	}
	if in.Compat != nil {
		in, out := &in.Compat, &out.Compat
		*out = make([]CatalogItemCompat, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TemplateCatalogCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *CatalogItemStatus) DeepCopy() *CatalogItemStatus {
	if in == nil {
		return nil
	}
	out := new(CatalogItemStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *CatalogItemCompat) DeepCopyInto(out *CatalogItemCompat) {
	*out = *in
}

func (in *CatalogItemCompat) DeepCopy() *CatalogItemCompat {
	if in == nil {
		return nil
	}
	out := new(CatalogItemCompat)
	in.DeepCopyInto(out)
	return out
}

func (in *CatalogItemClosureEntry) DeepCopyInto(out *CatalogItemClosureEntry) {
	*out = *in
}

func (in *CatalogItemClosureEntry) DeepCopy() *CatalogItemClosureEntry {
	if in == nil {
		return nil
	}
	out := new(CatalogItemClosureEntry)
	in.DeepCopyInto(out)
	return out
}

func (in *CatalogVariable) DeepCopyInto(out *CatalogVariable) {
	*out = *in
	if in.AllowedValues != nil {
		in, out := &in.AllowedValues, &out.AllowedValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// ---- ComposedBundle ----

func (in *ComposedBundle) DeepCopyInto(out *ComposedBundle) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *ComposedBundle) DeepCopy() *ComposedBundle {
	if in == nil {
		return nil
	}
	out := new(ComposedBundle)
	in.DeepCopyInto(out)
	return out
}

func (in *ComposedBundle) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ComposedBundleList) DeepCopyInto(out *ComposedBundleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ComposedBundle, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *ComposedBundleList) DeepCopy() *ComposedBundleList {
	if in == nil {
		return nil
	}
	out := new(ComposedBundleList)
	in.DeepCopyInto(out)
	return out
}

func (in *ComposedBundleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *ComposedBundleSpec) DeepCopyInto(out *ComposedBundleSpec) {
	*out = *in
	if in.Inputs != nil {
		in, out := &in.Inputs, &out.Inputs
		*out = make([]ComposedInput, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

func (in *ComposedItemRef) DeepCopyInto(out *ComposedItemRef) {
	*out = *in
	if in.Variables != nil {
		in, out := &in.Variables, &out.Variables
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

func (in *ComposedItemRef) DeepCopy() *ComposedItemRef {
	if in == nil {
		return nil
	}
	out := new(ComposedItemRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ComposedInput.
func (in *ComposedInput) DeepCopyInto(out *ComposedInput) {
	*out = *in
	if in.ItemRef != nil {
		in, out := &in.ItemRef, &out.ItemRef
		*out = new(ComposedItemRef)
		(*in).DeepCopyInto(*out)
	}
	if in.GitSource != nil {
		in, out := &in.GitSource, &out.GitSource
		*out = new(GitBundleSource)
		**out = **in
	}
	if in.OCISource != nil {
		in, out := &in.OCISource, &out.OCISource
		*out = new(OCIBundleSource)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy for ComposedInput.
func (in *ComposedInput) DeepCopy() *ComposedInput {
	if in == nil {
		return nil
	}
	out := new(ComposedInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for GitBundleSource.
func (in *GitBundleSource) DeepCopyInto(out *GitBundleSource) {
	*out = *in
}

// DeepCopy for GitBundleSource.
func (in *GitBundleSource) DeepCopy() *GitBundleSource {
	if in == nil {
		return nil
	}
	out := new(GitBundleSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for OCIBundleSource.
func (in *OCIBundleSource) DeepCopyInto(out *OCIBundleSource) {
	*out = *in
}

// DeepCopy for OCIBundleSource.
func (in *OCIBundleSource) DeepCopy() *OCIBundleSource {
	if in == nil {
		return nil
	}
	out := new(OCIBundleSource)
	in.DeepCopyInto(out)
	return out
}

func (in *ComposedBundleRef) DeepCopyInto(out *ComposedBundleRef) {
	*out = *in
}

func (in *ComposedBundleStatus) DeepCopyInto(out *ComposedBundleStatus) {
	*out = *in
	if in.MissingItems != nil {
		in, out := &in.MissingItems, &out.MissingItems
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DriftedItems != nil {
		in, out := &in.DriftedItems, &out.DriftedItems
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]TemplateCatalogCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ObservedRevisions != nil {
		in, out := &in.ObservedRevisions, &out.ObservedRevisions
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
	if in.Errors != nil {
		in, out := &in.Errors, &out.Errors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Warnings != nil {
		in, out := &in.Warnings, &out.Warnings
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.InputSummary != nil {
		in, out := &in.InputSummary, &out.InputSummary
		*out = make([]InputSummaryEntry, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for RBACSpec.
func (in *RBACSpec) DeepCopyInto(out *RBACSpec) {
	*out = *in
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]RBACGroupBinding, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for RBACGroupBinding.
func (in *RBACGroupBinding) DeepCopyInto(out *RBACGroupBinding) {
	*out = *in
}

// DeepCopyInto for SizePreset.
func (in *SizePreset) DeepCopyInto(out *SizePreset) {
	*out = *in
}

// DeepCopyInto for InputSummaryEntry.
func (in *InputSummaryEntry) DeepCopyInto(out *InputSummaryEntry) {
	*out = *in
}

// DeepCopyInto for PodOverrides.
func (in *PodOverrides) DeepCopyInto(out *PodOverrides) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Volumes != nil {
		in, out := &in.Volumes, &out.Volumes
		*out = make([]corev1.Volume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VolumeMounts != nil {
		in, out := &in.VolumeMounts, &out.VolumeMounts
		*out = make([]corev1.VolumeMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of PodOverrides.
func (in *PodOverrides) DeepCopy() *PodOverrides {
	if in == nil {
		return nil
	}
	out := new(PodOverrides)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ResourceOverlay.
func (in *ResourceOverlay) DeepCopyInto(out *ResourceOverlay) {
	*out = *in
}

// DeepCopy creates a deep copy of ResourceOverlay.
func (in *ResourceOverlay) DeepCopy() *ResourceOverlay {
	if in == nil {
		return nil
	}
	out := new(ResourceOverlay)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for OverlayWarning.
func (in *OverlayWarning) DeepCopyInto(out *OverlayWarning) {
	*out = *in
}

// DeepCopy creates a deep copy of OverlayWarning.
func (in *OverlayWarning) DeepCopy() *OverlayWarning {
	if in == nil {
		return nil
	}
	out := new(OverlayWarning)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for JenkinsVersionProfile.
func (in *JenkinsVersionProfile) DeepCopyInto(out *JenkinsVersionProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of JenkinsVersionProfile.
func (in *JenkinsVersionProfile) DeepCopy() *JenkinsVersionProfile {
	if in == nil {
		return nil
	}
	out := new(JenkinsVersionProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *JenkinsVersionProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for JenkinsVersionProfileList.
func (in *JenkinsVersionProfileList) DeepCopyInto(out *JenkinsVersionProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JenkinsVersionProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of JenkinsVersionProfileList.
func (in *JenkinsVersionProfileList) DeepCopy() *JenkinsVersionProfileList {
	if in == nil {
		return nil
	}
	out := new(JenkinsVersionProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *JenkinsVersionProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for JenkinsVersionProfileSpec.
func (in *JenkinsVersionProfileSpec) DeepCopyInto(out *JenkinsVersionProfileSpec) {
	*out = *in
	if in.PluginSetRef != nil {
		in, out := &in.PluginSetRef, &out.PluginSetRef
		*out = new(ConfigMapRef)
		**out = **in
	}
	if in.JCasC != nil {
		in, out := &in.JCasC, &out.JCasC
		*out = new(VersionJCasC)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopyInto for ConfigMapRef.
func (in *ConfigMapRef) DeepCopyInto(out *ConfigMapRef) {
	*out = *in
}

// DeepCopyInto for VersionJCasC.
func (in *VersionJCasC) DeepCopyInto(out *VersionJCasC) {
	*out = *in
	if in.RequiredPlugins != nil {
		in, out := &in.RequiredPlugins, &out.RequiredPlugins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopyInto for JenkinsVersionProfileStatus.
func (in *JenkinsVersionProfileStatus) DeepCopyInto(out *JenkinsVersionProfileStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]JenkinsVersionProfileCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopyInto for JenkinsVersionProfileCondition.
func (in *JenkinsVersionProfileCondition) DeepCopyInto(out *JenkinsVersionProfileCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

// ---- UpdateCenter ----

func (in *UpdateCenter) DeepCopyInto(out *UpdateCenter) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *UpdateCenter) DeepCopy() *UpdateCenter {
	if in == nil {
		return nil
	}
	out := new(UpdateCenter)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenter) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *UpdateCenterList) DeepCopyInto(out *UpdateCenterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]UpdateCenter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *UpdateCenterList) DeepCopy() *UpdateCenterList {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterList)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *UpdateCenterSpec) DeepCopyInto(out *UpdateCenterSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	in.Seed.DeepCopyInto(&out.Seed)
}

func (in *UpdateCenterSpec) DeepCopy() *UpdateCenterSpec {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterStorage) DeepCopyInto(out *UpdateCenterStorage) {
	*out = *in
	if in.OCI != nil {
		in, out := &in.OCI, &out.OCI
		*out = new(UpdateCenterOCIStorage)
		**out = **in
	}
	if in.Local != nil {
		in, out := &in.Local, &out.Local
		*out = new(UpdateCenterLocalStorage)
		**out = **in
	}
}

func (in *UpdateCenterStorage) DeepCopy() *UpdateCenterStorage {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterStorage)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterOCIStorage) DeepCopyInto(out *UpdateCenterOCIStorage) {
	*out = *in
}

func (in *UpdateCenterOCIStorage) DeepCopy() *UpdateCenterOCIStorage {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterOCIStorage)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterLocalStorage) DeepCopyInto(out *UpdateCenterLocalStorage) {
	*out = *in
}

func (in *UpdateCenterLocalStorage) DeepCopy() *UpdateCenterLocalStorage {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterLocalStorage)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterPullThrough) DeepCopyInto(out *UpdateCenterPullThrough) {
	*out = *in
}

func (in *UpdateCenterPullThrough) DeepCopy() *UpdateCenterPullThrough {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterPullThrough)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterSeed) DeepCopyInto(out *UpdateCenterSeed) {
	*out = *in
	if in.Refs != nil {
		in, out := &in.Refs, &out.Refs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *UpdateCenterSeed) DeepCopy() *UpdateCenterSeed {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterSeed)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterStatus) DeepCopyInto(out *UpdateCenterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]UpdateCenterCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Gaps != nil {
		in, out := &in.Gaps, &out.Gaps
		*out = make([]UpdateCenterGap, len(*in))
		copy(*out, *in)
	}
	in.LastSyncTime.DeepCopyInto(&out.LastSyncTime)
	if in.SeedImportedDigests != nil {
		in, out := &in.SeedImportedDigests, &out.SeedImportedDigests
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ResolvedMetadataSources != nil {
		in, out := &in.ResolvedMetadataSources, &out.ResolvedMetadataSources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

func (in *UpdateCenterStatus) DeepCopy() *UpdateCenterStatus {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterCondition) DeepCopyInto(out *UpdateCenterCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
}

func (in *UpdateCenterCondition) DeepCopy() *UpdateCenterCondition {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterCondition)
	in.DeepCopyInto(out)
	return out
}

func (in *UpdateCenterGap) DeepCopyInto(out *UpdateCenterGap) {
	*out = *in
}

func (in *UpdateCenterGap) DeepCopy() *UpdateCenterGap {
	if in == nil {
		return nil
	}
	out := new(UpdateCenterGap)
	in.DeepCopyInto(out)
	return out
}

// ---- BroodOperation ----

func (in *BroodOperation) DeepCopyInto(out *BroodOperation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *BroodOperation) DeepCopy() *BroodOperation {
	if in == nil {
		return nil
	}
	out := new(BroodOperation)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodOperation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BroodOperationList) DeepCopyInto(out *BroodOperationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BroodOperation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BroodOperationList) DeepCopy() *BroodOperationList {
	if in == nil {
		return nil
	}
	out := new(BroodOperationList)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodOperationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BroodOperationSpec) DeepCopyInto(out *BroodOperationSpec) {
	*out = *in
	out.Action = in.Action
	in.Targets.DeepCopyInto(&out.Targets)
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(BroodExecution)
		(*in).DeepCopyInto(*out)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

func (in *BroodOperationSpec) DeepCopy() *BroodOperationSpec {
	if in == nil {
		return nil
	}
	out := new(BroodOperationSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodAction) DeepCopyInto(out *BroodAction) {
	*out = *in
	if in.Groovy != nil {
		in, out := &in.Groovy, &out.Groovy
		*out = new(BroodGroovyAction)
		(*in).DeepCopyInto(*out)
	}
}

func (in *BroodAction) DeepCopy() *BroodAction {
	if in == nil {
		return nil
	}
	out := new(BroodAction)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodGroovyAction) DeepCopyInto(out *BroodGroovyAction) {
	*out = *in
	if in.ItemRef != nil {
		in, out := &in.ItemRef, &out.ItemRef
		*out = new(ComposedItemRef)
		(*in).DeepCopyInto(*out)
	}
}

func (in *BroodGroovyAction) DeepCopy() *BroodGroovyAction {
	if in == nil {
		return nil
	}
	out := new(BroodGroovyAction)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodTargets) DeepCopyInto(out *BroodTargets) {
	*out = *in
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(metav1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.Namespaces != nil {
		in, out := &in.Namespaces, &out.Namespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Filters != nil {
		in, out := &in.Filters, &out.Filters
		*out = new(BroodTargetFilters)
		(*in).DeepCopyInto(*out)
	}
}

func (in *BroodTargets) DeepCopy() *BroodTargets {
	if in == nil {
		return nil
	}
	out := new(BroodTargets)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodTargetFilters) DeepCopyInto(out *BroodTargetFilters) {
	*out = *in
	if in.Phase != nil {
		in, out := &in.Phase, &out.Phase
		*out = new(ControllerPhase)
		**out = **in
	}
	if in.Version != nil {
		in, out := &in.Version, &out.Version
		*out = new(string)
		**out = **in
	}
	if in.Bundle != nil {
		in, out := &in.Bundle, &out.Bundle
		*out = new(string)
		**out = **in
	}
}

func (in *BroodTargetFilters) DeepCopy() *BroodTargetFilters {
	if in == nil {
		return nil
	}
	out := new(BroodTargetFilters)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodExecution) DeepCopyInto(out *BroodExecution) {
	*out = *in
	if in.MaxParallel != nil {
		in, out := &in.MaxParallel, &out.MaxParallel
		*out = new(int32)
		**out = **in
	}
}

func (in *BroodExecution) DeepCopy() *BroodExecution {
	if in == nil {
		return nil
	}
	out := new(BroodExecution)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodOperationStatus) DeepCopyInto(out *BroodOperationStatus) {
	*out = *in
	if in.StartedAt != nil {
		in, out := &in.StartedAt, &out.StartedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
	if in.Targets != nil {
		in, out := &in.Targets, &out.Targets
		*out = make([]BroodTargetStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BroodOperationStatus) DeepCopy() *BroodOperationStatus {
	if in == nil {
		return nil
	}
	out := new(BroodOperationStatus)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodTargetStatus) DeepCopyInto(out *BroodTargetStatus) {
	*out = *in
	if in.DispatchedAt != nil {
		in, out := &in.DispatchedAt, &out.DispatchedAt
		*out = (*in).DeepCopy()
	}
	if in.FinishedAt != nil {
		in, out := &in.FinishedAt, &out.FinishedAt
		*out = (*in).DeepCopy()
	}
}

func (in *BroodTargetStatus) DeepCopy() *BroodTargetStatus {
	if in == nil {
		return nil
	}
	out := new(BroodTargetStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for BroodSummary.
func (in *BroodSummary) DeepCopyInto(out *BroodSummary) {
	*out = *in
}

// DeepCopy creates a deep copy of BroodSummary.
func (in *BroodSummary) DeepCopy() *BroodSummary {
	if in == nil {
		return nil
	}
	out := new(BroodSummary)
	in.DeepCopyInto(out)
	return out
}

// ---- BroodSchedule ----

func (in *BroodSchedule) DeepCopyInto(out *BroodSchedule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *BroodSchedule) DeepCopy() *BroodSchedule {
	if in == nil {
		return nil
	}
	out := new(BroodSchedule)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodSchedule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BroodScheduleList) DeepCopyInto(out *BroodScheduleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BroodSchedule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BroodScheduleList) DeepCopy() *BroodScheduleList {
	if in == nil {
		return nil
	}
	out := new(BroodScheduleList)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodScheduleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *BroodScheduleSpec) DeepCopyInto(out *BroodScheduleSpec) {
	*out = *in
	if in.StartingDeadlineSeconds != nil {
		in, out := &in.StartingDeadlineSeconds, &out.StartingDeadlineSeconds
		*out = new(int64)
		**out = **in
	}
	if in.SuccessfulJobsHistoryLimit != nil {
		in, out := &in.SuccessfulJobsHistoryLimit, &out.SuccessfulJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	if in.FailedJobsHistoryLimit != nil {
		in, out := &in.FailedJobsHistoryLimit, &out.FailedJobsHistoryLimit
		*out = new(int32)
		**out = **in
	}
	in.Template.DeepCopyInto(&out.Template)
}

func (in *BroodScheduleSpec) DeepCopy() *BroodScheduleSpec {
	if in == nil {
		return nil
	}
	out := new(BroodScheduleSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodScheduleTemplate) DeepCopyInto(out *BroodScheduleTemplate) {
	*out = *in
	in.Targets.DeepCopyInto(&out.Targets)
	out.Action = in.Action
	if in.Clusters != nil {
		in, out := &in.Clusters, &out.Clusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Execution != nil {
		in, out := &in.Execution, &out.Execution
		*out = new(BroodExecution)
		(*in).DeepCopyInto(*out)
	}
	if in.TTLSecondsAfterFinished != nil {
		in, out := &in.TTLSecondsAfterFinished, &out.TTLSecondsAfterFinished
		*out = new(int32)
		**out = **in
	}
}

func (in *BroodScheduleTemplate) DeepCopy() *BroodScheduleTemplate {
	if in == nil {
		return nil
	}
	out := new(BroodScheduleTemplate)
	in.DeepCopyInto(out)
	return out
}

func (in *BroodScheduleStatus) DeepCopyInto(out *BroodScheduleStatus) {
	*out = *in
	if in.LastScheduleTime != nil {
		in, out := &in.LastScheduleTime, &out.LastScheduleTime
		*out = (*in).DeepCopy()
	}
	if in.LastSuccessfulTime != nil {
		in, out := &in.LastSuccessfulTime, &out.LastSuccessfulTime
		*out = (*in).DeepCopy()
	}
	if in.Active != nil {
		in, out := &in.Active, &out.Active
		*out = make([]corev1.ObjectReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *BroodScheduleStatus) DeepCopy() *BroodScheduleStatus {
	if in == nil {
		return nil
	}
	out := new(BroodScheduleStatus)
	in.DeepCopyInto(out)
	return out
}

// ---- ImperativeResult ----

func (in *ImperativeResult) DeepCopyInto(out *ImperativeResult) {
	*out = *in
	in.FinishedAt.DeepCopyInto(&out.FinishedAt)
}

func (in *ImperativeResult) DeepCopy() *ImperativeResult {
	if in == nil {
		return nil
	}
	out := new(ImperativeResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for HibernationSpec.
func (in *HibernationSpec) DeepCopyInto(out *HibernationSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of HibernationSpec.
func (in *HibernationSpec) DeepCopy() *HibernationSpec {
	if in == nil {
		return nil
	}
	out := new(HibernationSpec)
	in.DeepCopyInto(out)
	return out
}

// ---- ControllerClass ----

// DeepCopyInto for ControllerClass.
func (in *ControllerClass) DeepCopyInto(out *ControllerClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of ControllerClass.
func (in *ControllerClass) DeepCopy() *ControllerClass {
	if in == nil {
		return nil
	}
	out := new(ControllerClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ControllerClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for ControllerClassList.
func (in *ControllerClassList) DeepCopyInto(out *ControllerClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ControllerClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ControllerClassList.
func (in *ControllerClassList) DeepCopy() *ControllerClassList {
	if in == nil {
		return nil
	}
	out := new(ControllerClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *ControllerClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto for ControllerClassSpec.
func (in *ControllerClassSpec) DeepCopyInto(out *ControllerClassSpec) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(corev1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PodLabels != nil {
		in, out := &in.PodLabels, &out.PodLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodAnnotations != nil {
		in, out := &in.PodAnnotations, &out.PodAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.IngressAnnotations != nil {
		in, out := &in.IngressAnnotations, &out.IngressAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(corev1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Persistence != nil {
		in, out := &in.Persistence, &out.Persistence
		*out = new(PersistenceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = new(ProbesSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Mite != nil {
		in, out := &in.Mite, &out.Mite
		*out = new(ClassMiteSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ImagePullSecrets != nil {
		in, out := &in.ImagePullSecrets, &out.ImagePullSecrets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy creates a deep copy of ControllerClassSpec.
func (in *ControllerClassSpec) DeepCopy() *ControllerClassSpec {
	if in == nil {
		return nil
	}
	out := new(ControllerClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ControllerClassStatus.
func (in *ControllerClassStatus) DeepCopyInto(out *ControllerClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of ControllerClassStatus.
func (in *ControllerClassStatus) DeepCopy() *ControllerClassStatus {
	if in == nil {
		return nil
	}
	out := new(ControllerClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for ClassMiteSpec.
func (in *ClassMiteSpec) DeepCopyInto(out *ClassMiteSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of ClassMiteSpec.
func (in *ClassMiteSpec) DeepCopy() *ClassMiteSpec {
	if in == nil {
		return nil
	}
	out := new(ClassMiteSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function for PluginInventoryStatus.
func (in *PluginInventoryStatus) DeepCopyInto(out *PluginInventoryStatus) {
	*out = *in
	if in.CollectedAt != nil {
		in, out := &in.CollectedAt, &out.CollectedAt
		*out = (*in).DeepCopy()
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
	if in.Counts != nil {
		in, out := &in.Counts, &out.Counts
		*out = make(map[string]int, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Drift != nil {
		in, out := &in.Drift, &out.Drift
		*out = make([]PluginInventoryDriftEntry, len(*in))
		copy(*out, *in)
	}
	if in.VersionDrift != nil {
		in, out := &in.VersionDrift, &out.VersionDrift
		*out = make([]PluginInventoryDriftEntry, len(*in))
		copy(*out, *in)
	}
	if in.PendingCollect != nil {
		in, out := &in.PendingCollect, &out.PendingCollect
		*out = new(PendingCollect)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy creates a deep copy of PluginInventoryStatus.
func (in *PluginInventoryStatus) DeepCopy() *PluginInventoryStatus {
	if in == nil {
		return nil
	}
	out := new(PluginInventoryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for PluginInventoryDriftEntry (no pointer fields).
func (in *PluginInventoryDriftEntry) DeepCopyInto(out *PluginInventoryDriftEntry) {
	*out = *in
}

// DeepCopy creates a deep copy of PluginInventoryDriftEntry.
func (in *PluginInventoryDriftEntry) DeepCopy() *PluginInventoryDriftEntry {
	if in == nil {
		return nil
	}
	out := new(PluginInventoryDriftEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto for PendingCollect.
func (in *PendingCollect) DeepCopyInto(out *PendingCollect) {
	*out = *in
	in.IssuedAt.DeepCopyInto(&out.IssuedAt)
}

// DeepCopy creates a deep copy of PendingCollect.
func (in *PendingCollect) DeepCopy() *PendingCollect {
	if in == nil {
		return nil
	}
	out := new(PendingCollect)
	in.DeepCopyInto(out)
	return out
}
